version: '3.7'

services:
  app:
    restart: always
    build:
      context: .
      target: app-container
    volumes:
      - ./docker/test_app:/app/test_app
      - ./uw_spotseeker:/app/uw_spotseeker
    ports:
      - "${PORT:-8003}:8000"
    environment:
      ENV: localdev
      APP_NAME: ${APP_NAME:-test-app}
      OAUTH_USER: ${OAUTH_USER:-javerage}
      RESTCLIENTS_SPOTSEEKER_HOST: ${RESTCLIENTS_SPOTSEEKER_HOST:-None}
      RESTCLIENTS_SPOTSEEKER_DAO_CLASS: ${RESTCLIENTS_SPOTSEEKER_DAO_CLASS:-Mock}
      CREDENTIAL: ${CREDENTIAL:-None}
      SPOTSEEKER_OAUTH_SCOPE: ${SPOTSEEKER_OAUTH_SCOPE:-read}
      DEBUG_CACHING: ${DEBUG_CACHING:-True}
    stdin_open: true
    tty: true
