name: 'Lint and Test'

env: uw_spotseeker

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install commonconf nose2 coverage coveralls==2.2.0
      
      - name: Run Python Linters
        uses: uw-it-aca/actions/python-linters@main
        with:
          app_name: ${APP_NAME}

      - name: Run Tests
        run: |
          python -m compileall ${APP_NAME}/
          coverage run ${APP_NAME}/test.py -v
      
      - name: Report Test Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: coveralls