name: 'Lint and Test'

env: uw_spotseeker

on:
  push:
    branches: [main, master, qa, develop]
  pull_request:
    branches: [main, master, qa, develop]
    types: [opened, reopened, synchronize]
  release:
    branches: [main, master]
    types: [published]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install commonconf nose2 coverage coveralls==2.2.0
      
      - name: Run Python Linters
        uses: uw-it-aca/actions/python-linters@main
        with:
          app_name: ${APP_NAME}

      - name: Run Tests
        run: |
          python -m compileall ${APP_NAME}/
          coverage run ${APP_NAME}/test.py -v
      
      - name: Report Test Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: coveralls

  publish:
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')

    needs: test

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Publish to PyPi
        uses: uw-it-aca/actions/publish-pypi@main
        with:
          app_name: ${APP_NAME}
          tag_name: ${{ github.event.release.tag_name }}
          api_token: ${{ secrets.PYPI_API_TOKEN }}